# Generated by Django 2.1.8 on 2022-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('current_date', models.DateField(verbose_name='更新时间')),
                ('location', models.CharField(max_length=20, verbose_name='地区')),
                ('incr_confirmed', models.PositiveIntegerField(default=0, verbose_name='新增确诊人数')),
                ('incr_cured', models.PositiveIntegerField(default=0, verbose_name='新增治愈人数')),
                ('incr_dead', models.PositiveIntegerField(default=0, verbose_name='新增死亡人数')),
                ('incr_suspected', models.PositiveIntegerField(default=0, verbose_name='新增疑似人数')),
            ],
            options={
                'verbose_name_plural': '当日疫情数据',
                'db_table': 'covid_current',
            },
        ),
        migrations.CreateModel(
            name='CovidHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='更新时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('location', models.CharField(max_length=20, verbose_name='地区')),
                ('total_confirmed', models.IntegerField(default=0, verbose_name='累计确诊人数')),
                ('total_cured', models.IntegerField(default=0, verbose_name='累计治愈人数')),
                ('total_dead', models.IntegerField(default=0, verbose_name='累计死亡人数')),
            ],
            options={
                'verbose_name_plural': '疫情数据汇总',
                'db_table': 'covid_history',
            },
        ),
    ]
