# Generated by Django 2.1.8 on 2022-03-12 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covidmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidcurrent',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='covidcurrent',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='covidhistory',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='covidhistory',
            name='update_time',
        ),
        migrations.AddField(
            model_name='covidcurrent',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='covidcurrent',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='covidhistory',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='covidhistory',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
