# Generated by Django 2.1.8 on 2022-03-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidmap', '0002_auto_20220312_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
            },
        ),
        migrations.AlterField(
            model_name='covidcurrent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='covidcurrent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidmap.Location', verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='covidhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='covidhistory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidmap.Location', verbose_name='地区'),
        ),
    ]
